[package]
name = "xml-tree"
version = "0.0.1"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]

[lib]
name = "xml_tree"
path = "src/lib.rs"
test = true

[dependencies]
xml-rs = "0.1.20"
